### ISSUE TITLE
Error retrieving

### ISSUE THREAD

**Issue by hamiltoncolares** [kejadlen/dark-sky.alfredworkflow#15]
Can anyone help with this error?

```
[2016-10-23 11:49:24][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
    from /Users/hamiltoncolares/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7C2DE732-3050-4A00-8467-E46E368EBEBA/forecaster.rb:19:in `forecast'
    from /Users/hamiltoncolares/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7C2DE732-3050-4A00-8467-E46E368EBEBA/forecaster.rb:6:in `forecast'
    from dark-sky.rb:59:in `<main>'
```

**Comment by kejadlen** [comment]
Did you set the `DARK_SKY_API_KEY`?

**Comment by hamiltoncolares** [comment]
Yes, I did.

**Comment by kejadlen** [comment]
@hamiltoncolares How familiar are you w/Ruby and are you comfortable doing a bit of debugging? If so, can you drop a `raise url` before [this line](https://github.com/kejadlen/dark-sky.alfredworkflow/blob/master/forecaster.rb#L19) to see what URL the workflow is trying to hit?
